// Code generated by Kitex v0.9.1. DO NOT EDIT.
package quizqueryservice

import (
	server "github.com/cloudwego/kitex/server"
	pb "ququiz/lintang/scoring-service/kitex_gen/quiz-query-service/pb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler pb.QuizQueryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler pb.QuizQueryService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
